### ch10. File io

10.1 read

10.2 write

10.3 exception

csv

json

In [ ]:
#10.1 open(파일이름, 파일 읽기 r / 쓰기 w) -> 직접열고 닫기
f = open('Numbers.txt','r', encoding='utf-8')
#f.read(5) #바이트 단위로 읽기
f.readline().rstrip() #줄 단위로 읽기 #rstrip() : 오른쪽 끝의 공백 문자를 제거합니다.
f.close()

In [15]:
# with 블록을 넘어가면 자동으로 파일 닫기
with open('Numbers.txt','r', encoding='utf-8') as f:
    print(f.readline(),' ')

1

In [18]:
with open('Numbers.txt','r', encoding='utf-8') as f:
    for line in f:
        print(line)

1

2

3

4

5

In [19]:
with open('Numbers.txt','r') as f:
    for line in f:
        print(line.rstrip())

1
2
3
4
5

In [24]:
with open('Numbers.txt','r') as f:
    contents = f.readlines()
    print(contents)

['1\n', '2\n', '3\n', '4\n', '5\n']

In [ ]:
#10.2 파일 쓰기
file = open('Numbers2.txt','w')
file.write('1'+'\n')
file.write('2'+'\n')
file.close()

In [32]:
file = open('Numbers2.txt','w')
answer = ['1','2','3']
contents = '\n'.join(answer)
file.write(contents)
file.close()

In [37]:
with open('Numbers2.txt','w') as file:
    answer = ['1','2','3','4']
    contents = '\n'.join(answer)
    file.write(contents)

In [43]:
with open('Numbers2.txt','w', encoding='utf-8') as f:
    f.writelines(['1','2','10'],'\n')

TypeError: _IOBase.writelines() takes exactly one argument (2 given)

In [47]:
from pathlib import Path

p = Path('Numbers.txt')
p.read_text().split()

['1', '2', '3', '4', '5']

In [50]:
from pathlib import Path

p = Path('Numbers2.txt')
answer = ['1','2','3','10']
contents = '\n'.join(answer)
p.write_text(contents)

8

In [ ]:
# with open('Numbers5.txt','w')as f:
#     f.write('a')

In [60]:
# 없는 파일을 읽으려면 -> 예외 발생 -> 예외 처리
try:
    with open('Numbers5.txt','r')as f:
        f.read()
except FileNotFoundError as e:
    print(e)
    print("ERROR!")

except Exception as e:
    print("UNKNOWN ERROR!")

[Errno 2] No such file or directory: 'Numbers5.txt'
ERROR!

In [62]:
def add(a,b):
    raise FileNotFoundError("Hello")

def main():
    try:
        add(1,2)
    except FileNotFoundError as e:
        print(e)
        print("ERROR!")

    except Exception as e:
        print("UNKNOWN ERROR!")

main()

Hello
ERROR!

In [63]:
def add(a,b):
    raise FileNotFoundError("Hello")

def main():
        add(1,2)

try:
    main()
except FileNotFoundError as e:
    print(e)
    print("ERROR!")

except Exception as e:
    print("UNKNOWN ERROR!")

Hello
ERROR!

In [66]:
#csv 파일
import csv
with open('grade.csv','r') as f:
    file = csv.reader(f)
    for line in file:
        print(line)

['name', 'java', 'python']
['kim', '90', '80']
['Lee', '77', '88']
['Park', ' 60', '50']

In [ ]:
# 학생별 평균
import csv
with open('grade.csv','r') as f:
    file = csv.reader(f)
    students = {}
    subjects = {}
    headers = next(file)
    for line in file:
        name = line[0]
        java = int(line[1])
        python = int(line[2])
        students[name] = sum([java,python])/2
        subjects['java'] = subjects.get('java', 0) + java
        subjects['python'] = subjects.get('python', 0) + python
students

{'kim': 85.0, 'Lee': 82.5, 'Park': 55.0}

In [79]:
# 과목별 평균 
for k,v in subjects.items():
    print(k,v / len(subjects))

java 113.5
python 109.0

In [ ]:
# pandas 라이브러리 사용하기 -> 앞으로 이용할 것임
import pandas as pd

df = pd.read_csv('grade.csv')
df.head()

   name  java  python
0   kim    90      80
1   Lee    77      88
2  Park    60      50

In [86]:
df.sum(axis=0)

name      kimLeePark
java             227
python           218
dtype: object

In [87]:
df.iloc[:,1:].sum(axis=0)

java      227
python    218
dtype: int64

In [88]:
df.describe()

            java     python
count   3.000000   3.000000
mean   75.666667  72.666667
std    15.044379  20.033306
min    60.000000  50.000000
25%    68.500000  65.000000
50%    77.000000  80.000000
75%    83.500000  84.000000
max    90.000000  88.000000

In [111]:
#json 파일 :  딕셔너리와 매우 유사한 형식을 가진 문자열

import json

In [ ]:
lst = [1,2,3]
contents = json.dumps(lst) # json.dumps(): Python 객체 → JSON 형식의 문자열(String)로 변환

In [ ]:
requset = json.loads(contents) # json.loads(): JSON 형식의 문자열(String) → Python 객체로 변환
type(requset), requset

(list, [1, 2, 3])

In [94]:
import json

In [95]:
data1 = {
	'kim' :	[90,80],
	'Lee' :	[77,88],
    'Park' : [60,50]  
        }

data = {
	'name' : ['kim','Lee','Park'],
	'java' :[90,77,60],
	'python' :[80,88,50]
        }

response = json.dumps(data)

In [98]:
request = json.loads(response)
type(request), requset

(dict,
 {'name': ['kim', 'Lee', 'Park'],
  'java': [90, 77, 60],
  'python': [80, 88, 50]})

In [105]:
import json
with open('data2.bin','w')as f:
    json.dump(data, f)

In [106]:
with open('data2.bin','r')as f:
    data2 = json.load(f)
data2

{'name': ['kim', 'Lee', 'Park'], 'java': [90, 77, 60], 'python': [80, 88, 50]}

In [108]:
data = {
	'name' : ['kim','Lee','Park'],
	'java' :[90,77,60],
	'python' :[80,88,50]
        }

with open('data.json','w')as f:
    json.dump(data, f)

In [115]:
# pickle 모듈 -> 바이너리 형식이기 때문에 읽기 힘듦
import pickle
with open('data.bin','wb')as f:
    pickle.dump(data, f)

In [104]:
with open('data.bin','rb')as f:
    data2 = pickle.load(f)

data2

{'name': ['kim', 'Lee', 'Park'], 'java': [90, 77, 60], 'python': [80, 88, 50]}

In [114]:
import csv
with open('grade.csv','r')as f:
    reader = csv.DictReader(f)
    for line in reader:
        print(line['name'])
        print(line['java'])
        print(line['python'])

kim
90
80
Lee
77
88
Park
60
50